remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Midhun K
description: Thank you for visiting my portfolio website! Here, you'll find information about me, explore my projects, and much more.
logo: assets/images/Logo.png
github:
  linkedin_url: https://www.linkedin.com/in/midhunkalavara/
