remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Midhun K
description: Welcome! I'm a data analyst with a passion for clear communication and data-driven decision making. I invite you to explore my projects and learn how I can contribute to your success.
logo: assets/images/new_logo.png
